site_name: KiCad Sharepoint Documentation
site_description: Common KiCAD library for Longhorn Racing Solar
site_author: LHR - Solar

theme:
  name: material
  favicon: LHRs.ico
  palette:
  - scheme: slate
    primary: blue

nav:
  - Home: 'README.md'
  - KiCad Setup: 'KiCad-Setup.md'
  - PCB Design Guidelines: 'Design.md'
    - Standards: 'Standards.md'
    - Workflow: 'Workflow.md'
  - Shared Components: 'Components.md'
    - Sharepoint Setup: 'Sharepoint-Setup.md'
    - Design Blocks: 'Blocks.md'
    - Common Parts: 'Parts.md'
  - JLC Ordering: 'Ordering.md'
  - PCB Assembly: 'Assembly.md'
  - Exporting Models: 'Export.md'
  - Jobsets: 'Jobsets.md'
  - Resources: 'Resources.md'

plugins:
  - search:
      prebuild_index: true
      lang: en
  - redirects:
      redirect_maps: {}

extra_javascript: []
extra_css: []
