site_name: KiCad Sharepoint Documentation
site_description: Common KiCAD library for Longhorn Racing Solar
site_author: LHR - Solar

theme:
  name: material
  favicon: LHRs.ico
  palette:
  - scheme: slate
    primary: blue

nav:
  - Home: 'README.md'
  - Assembly: 'Assembly.md'
  - Design Blocks: 'Blocks.md'
  - Exporting Models: 'Export.md'
  - Jobsets: 'Jobsets.md'
  - JLC Ordering: 'Ordering.md'
  - Common Components: 'Components.md'
  - KiCad Setup: 'Setup.md'
  - Design Standards: 'Standards.md'
  - Design Workflow: 'Workflow.md'

plugins:
  - search:
      prebuild_index: true
      lang: en
  - redirects:
      redirect_maps: {}

extra_javascript: []
extra_css: []
